<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Builder;

/**
 * Class ResellerLink
 *
 * Represents a unique link generated by a reseller for a specific product.
 *
 * @package App\Models
 * @property int $id
 * @property int $product_id The ID of the product being resold.
 * @property int $reseller_id The ID of the user who is the reseller.
 * @property string $code The unique code for the reseller link.
 * @property float $commission_rate The commission percentage the reseller earns on a sale.
 * @property float $total_earned The total commission amount earned through this link.
 * @property int $clicks_count The number of times the link has been clicked.
 * @property int $sales_count The number of sales made through this link.
 * @property bool $is_active Whether the link is currently active.
 * @property \Illuminate\Support\Carbon|null $last_clicked_at Timestamp of the last time the link was clicked.
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 *
 * @property-read Product $product The product being resold.
 * @property-read User $reseller The user who owns the reseller link.
 * @property-read \Illuminate\Database\Eloquent\Collection|Order[] $orders The orders generated through this link.
 * @property-read string $url The full URL for the reseller link.
 */
class ResellerLink extends Model
{
    use HasFactory;

    protected $fillable = [
        'product_id',
        'reseller_id',
        'code',
        'commission_rate',
        'total_earned',
        'clicks_count',
        'sales_count',
        'is_active',
        'last_clicked_at',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'commission_rate' => 'decimal:2',
            'total_earned' => 'decimal:2',
            'is_active' => 'boolean',
            'last_clicked_at' => 'datetime',
        ];
    }

    /**
     * The "booted" method of the model.
     *
     * Automatically generates a unique code when a new reseller link is created.
     *
     * @return void
     */
    protected static function boot(): void
    {
        parent::boot();

        static::creating(function ($resellerLink) {
            if (empty($resellerLink->code)) {
                $resellerLink->code = strtoupper(Str::random(8));
            }
        });
    }

    /**
     * Get the product being resold.
     *
     * @return BelongsTo
     */
    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    /**
     * Get the reseller (user) who owns this link.
     *
     * @return BelongsTo
     */
    public function reseller(): BelongsTo
    {
        return $this->belongsTo(User::class, 'reseller_id');
    }

    /**
     * Get the orders that were placed using this reseller link.
     *
     * @return HasMany
     */
    public function orders(): HasMany
    {
        return $this->hasMany(Order::class);
    }

    /**
     * Scope a query to only include active reseller links.
     *
     * @param Builder $query
     * @return Builder
     */
    public function scopeActive(Builder $query): Builder
    {
        return $query->where('reseller_links.is_active', true);
    }

    /**
     * Get the full URL for the reseller link.
     *
     * @return string
     */
    public function getUrlAttribute(): string
    {
        return $this->product->url . '?ref=' . $this->code;
    }

    /**
     * Record a click on this reseller link.
     *
     * Increments the click count and updates the last clicked timestamp.
     *
     * @return void
     */
    public function recordClick(): void
    {
        $this->increment('clicks_count');
        $this->update(['last_clicked_at' => now()]);
    }

    /**
     * Record a sale made through this reseller link.
     *
     * Increments the sales count and the total commission earned.
     *
     * @param float $commissionAmount The amount of commission earned from the sale.
     * @return void
     */
    public function recordSale(float $commissionAmount): void
    {
        $this->increment('sales_count');
        $this->increment('total_earned', $commissionAmount);
    }

    /**
     * Calculate the commission for a given sale amount based on the link's commission rate.
     *
     * @param float $amount The total amount of the sale.
     * @return float The calculated commission amount.
     */
    public function calculateCommission(float $amount): float
    {
        return ($amount * $this->commission_rate) / 100;
    }
}
